import swaggerJsdoc from 'swagger-jsdoc';

const options: swaggerJsdoc.Options = {
  definition: {
    openapi: '3.0.0',
    info: {
      title: 'Idempotency Gateway — Pay-Once Protocol',
      version: '1.0.0',
      description:
        'A production-grade idempotency layer that guarantees every payment is processed exactly once, no matter how many times a client retries.',
    },
    servers: [{ url: 'http://localhost:3000', description: 'Local server' }],
    components: {
      parameters: {
        IdempotencyKey: {
          name: 'Idempotency-Key',
          in: 'header',
          required: true,
          description: 'Unique identifier for this operation (UUID recommended). Generated by the client.',
          schema: { type: 'string', example: '550e8400-e29b-41d4-a716-446655440000' },
        },
      },
      schemas: {
        PaymentRequest: {
          type: 'object',
          required: ['amount', 'currency'],
          properties: {
            amount: {
              type: 'number',
              description: 'Positive numeric value',
              example: 100,
            },
            currency: {
              type: 'string',
              description: 'Supported currencies',
              enum: ['GHS', 'USD', 'EUR', 'GBP', 'NGN'],
              example: 'GHS',
            },
          },
        },
        PaymentResponse: {
          type: 'object',
          properties: {
            status: { type: 'string', example: 'success' },
            message: { type: 'string', example: 'Charged 100 GHS' },
            transactionId: { type: 'string', example: 'TXN-1719000000000-AB12CD' },
            amount: { type: 'number', example: 100 },
            currency: { type: 'string', example: 'GHS' },
            processedAt: { type: 'string', format: 'date-time', example: '2025-01-01T12:00:02.000Z' },
          },
        },
        ErrorResponse: {
          type: 'object',
          properties: {
            error: { type: 'string' },
          },
        },
      },
    },
    paths: {
      '/health': {
        get: {
          tags: ['Health'],
          summary: 'Health check',
          description: 'Returns server health status.',
          responses: {
            200: {
              description: 'Server is healthy',
              content: {
                'application/json': {
                  schema: {
                    type: 'object',
                    properties: { status: { type: 'string', example: 'ok' } },
                  },
                },
              },
            },
          },
        },
      },
      '/api/process-payment': {
        post: {
          tags: ['Payments'],
          summary: 'Process a payment',
          description:
            'Processes a payment exactly once. Safe to retry with the same `Idempotency-Key` and body — duplicate requests return the cached response instantly without re-processing.',
          parameters: [{ $ref: '#/components/parameters/IdempotencyKey' }],
          requestBody: {
            required: true,
            content: {
              'application/json': {
                schema: { $ref: '#/components/schemas/PaymentRequest' },
              },
            },
          },
          responses: {
            201: {
              description: 'Payment processed successfully (first request) or cached response replayed (duplicate)',
              headers: {
                'X-Cache-Hit': {
                  description: 'Present with value `true` when the response is a cached replay',
                  schema: { type: 'string', example: 'true' },
                },
              },
              content: {
                'application/json': {
                  schema: { $ref: '#/components/schemas/PaymentResponse' },
                  examples: {
                    firstRequest: {
                      summary: 'First request — payment processed',
                      value: {
                        status: 'success',
                        message: 'Charged 100 GHS',
                        transactionId: 'TXN-1719000000000-AB12CD',
                        amount: 100,
                        currency: 'GHS',
                        processedAt: '2025-01-01T12:00:02.000Z',
                      },
                    },
                    duplicateRequest: {
                      summary: 'Duplicate request — cached replay (X-Cache-Hit: true)',
                      value: {
                        status: 'success',
                        message: 'Charged 100 GHS',
                        transactionId: 'TXN-1719000000000-AB12CD',
                        amount: 100,
                        currency: 'GHS',
                        processedAt: '2025-01-01T12:00:02.000Z',
                      },
                    },
                  },
                },
              },
            },
            400: {
              description: 'Missing or invalid request',
              content: {
                'application/json': {
                  schema: { $ref: '#/components/schemas/ErrorResponse' },
                  examples: {
                    missingKey: {
                      summary: 'Missing Idempotency-Key header',
                      value: { error: 'Missing required header: Idempotency-Key' },
                    },
                    invalidAmount: {
                      summary: 'Invalid amount',
                      value: { error: 'amount must be a positive number' },
                    },
                    invalidCurrency: {
                      summary: 'Unsupported currency',
                      value: { error: 'currency must be one of: GHS, USD, EUR, GBP, NGN' },
                    },
                  },
                },
              },
            },
            409: {
              description: 'Same Idempotency-Key reused with a different request body',
              content: {
                'application/json': {
                  schema: { $ref: '#/components/schemas/ErrorResponse' },
                  example: { error: 'Idempotency key already used for a different request body.' },
                },
              },
            },
            503: {
              description: 'A request with this key is already in-flight — timed out waiting for result',
              content: {
                'application/json': {
                  schema: { $ref: '#/components/schemas/ErrorResponse' },
                  example: { error: 'A request with this key is already being processed. Please retry shortly.' },
                },
              },
            },
          },
        },
      },
    },
  },
  apis: [],
};

export default swaggerJsdoc(options);
